[package]
name = "macros"
version = "0.1.0"
edition = "2021"

[lib]
proc_macro = true

[dependencies]
proc-macro2 = "1.0.70"
quote = "1.0"
syn = { version = "2.0", features = ["full", "extra-traits"] }
